version: '3'

services:
  nginx:
    build:
      context: .
      args:
        - DOMAIN_NAME=${DOMAIN_NAME:-localhost}
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - web
    labels:
      traefik.enable: "true"
      traefik.frontend.rule: "Host: baroustan.${DOMAIN_NAME:-localhost}, www.baroustan.${DOMAIN_NAME:-localhost}"

networks:
  web:
    external: true
