version: '3'

services:
  nginx:
    build:
      context: .
      args:
        - DOMAIN_NAME=${DOMAIN_NAME:-localhost}
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - web
    labels:
      traefik.enable: "true"
      traefik.http.routers.baroustan.rule: "Host(`baroustan.${DOMAIN_NAME:-localhost}`)"

networks:
  web:
    external: true
